language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage codecov
install:
  -  python -m pip install . --no-deps -vv 
script:
  - coverage run -m unittest discover -s tests/
after_success:
  - codecov
