name: plassembler_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - flye >=2.9
  - unicycler >=0.4.8
  - biopython >=1.76
  - minimap2 >=2.11
  - pandas
  - fastp >=0.18.0
  - chopper >=0.5.0
  - mash >=2.2
  - rasusa >=0.5.0
  # issues with pysam with conda recpie - see https://github.com/bioconda/bioconda-recipes/blob/2653adb4e1ebf32a6cbbedb08e5eec07c27d8c93/recipes/strainflye/meta.yaml#L5
  # so fixing pysam to be 0.15.2 or less 
  # will also fix samtools to be 1.9
  # I have tested it out with samtools 1.9 and pysam 0.15.2 - causes no issues. 
  # Plassembler only uses basic functions of these tools so not too surprising
  - pysam >0.12,<0.16
  - curl
  - tar
