name: plassembler
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - flye>=2.9
  - unicycler>=0.4.8
  - bwa>=0.7.17
  - samtools>=1.15.1
  - biopython>=1.78
  - minimap2>=2.24
  - pandas>=1.3.5
  - fastp>=0.23.2
  - porechop>=0.2.4
  - filtlong>=0.2.1
