name: plassembler_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - flye >=2.9
  - unicycler >=0.4.8
  - biopython >=1.76
  - minimap2 >=2.11
  - pandas
  - fastp >=0.18.0
  - chopper >=0.5.0
  - mash >=2.2
  - samtools >=1.10
  - rasusa >=0.5.0
  - pysam
  - curl
  - tar
